server:
  port: 8080
  
spring:
  application:
    name: gateway-service
  
zuul:
  routes:
    artists:
      path: /artist-service/**
      service-id: artist-service
    google:
      path: /google/**
      url: http://www.google.com/
    localartists:
      path: /artist-local/**
      url: http://localhost:52020/
      
eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://localhost:8761/eureka/